project:
  type: website

website:
  page-navigation: true
  title: "IME05-12547"
  description: "Mineração de Dados"
  
  opengraph: true
  twitter-card:
    creator: "@r_accioly"
    image: "images/md.png"

  page-footer:
    left: "Baseado em https://sta210-s22.github.io/website/"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/md.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/raccioly20
        text: "GitHub"
      - icon: twitter
        href: https://twitter.com/r_accioly
        text: "Twitter"    

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Informação da disciplina"
        contents:
          - href: visao-do-curso.qmd
            text: "Visão Geral"
          - href: index.qmd
            text: Cronograma
      - section: "Sobre"
        contents:
          - href: about.qmd
            text: Sobre
      - section: "RStudio Cloud"
        contents:
          - href: acesso-rstudio.qmd
            text: Acesso
      - section: "Conteúdo Semanal"
        contents:
          - href: semanas/Aula01.qmd
            text: "1ª Semana"
          - href: semanas/Aula02.qmd
            text: "2ª Semana"
          - href: semanas/Aula03.qmd
            text: "3ª Semana"
          - href: semanas/Aula04.qmd
            text: "4ª Semana"
          - href: semanas/Aula05.qmd
            text: "5ª Semana"
          - href: semanas/Aula06.qmd
            text: "6ª Semana"
          - href: semanas/Aula07.1.qmd
            text: "7ª Semana"
          - href: semanas/Aula07.2.qmd
            text: "8ª Semana"
          - href: semanas/Aula07.3.qmd
            text: "9ª Semana"
          - href: semanas/Aula07.3A.qmd
            text: "10ª Semana"
          - href: semanas/Aula07.4.qmd
            text: "11ª Semana"
          - href: semanas/Aula08.qmd
            text: "12ª Semana"
          - href: semanas/Aula09.qmd
            text: "13ª Semana"
          - href: semanas/Aula09A.qmd
            text: "14ª Semana"
          - href: semanas/Aula10.qmd
            text: "15ª Semana"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual

