project:
  type: website

website:
  page-navigation: true
  title: "IME05-12547"
  description: "Mineração de Dados"
  
  twitter-card:
    creator: "@r_accioly"
    image: "images/md.png"

  page-footer:
    left: "Baseado em https://sta210-s22.github.io/website/"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/md.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/raccioly20
        text: "GitHub"
      - icon: twitter
        href: https://twitter.com/r_accioly
        text: "Twitter"    

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Informação da disciplina"
        contents:
          - href: visao-do-curso.qmd
            text: "Visão Geral"
          - href: index.qmd
            text: Cronograma
      - section: "Sobre"
        contents:
          - href: about.qmd
            text: Sobre
      - section: "RStudio Cloud"
        contents:
          - href: acesso-rstudio.qmd
            text: Acesso
      - section: "Conteúdo Semanal"
        contents:
          - href: semanas/Aula01.qmd
            text: "Aula 01"
          - href: semanas/Aula01A.qmd
            text: "Aula 01A"
          - href: semanas/Aula02.qmd
            text: "Aula 02"
          - href: semanas/Aula03.qmd
            text: "Aula 03"
          - href: semanas/Aula04.qmd
            text: "Aula 04"
          - href: semanas/Aula05.qmd
            text: "Aula 05"
          - href: semanas/Aula06.qmd
            text: "Aula 06"
          - href: semanas/Aula07.1.qmd
            text: "Aula 07.1"
          - href: semanas/Aula07.2.qmd
            text: "Aula 07.2"
          - href: semanas/Aula07.2A.qmd
            text: "Aula 07.2A"
          - href: semanas/Aula07.3.qmd
            text: "Aula 7.3"
          - href: semanas/Aula07.4.qmd
            text: "Aula 7.4"
          - href: semanas/Aula08.0.qmd
            text: "Aula 08.0"
          - href: semanas/Aula08.qmd
            text: "Aula 08"
          - href: semanas/Aula09.qmd
            text: "Aula 09"
          - href: semanas/Aula09A.qmd
            text: "Aula 09A"
          - href: semanas/Aula10.qmd
            text: "Aula 10"
          - href: semanas/Aula11.qmd
            text: "Aula 11"
          - href: semanas/Aula12.qmd
            text: "Aula 12"
          - href: semanas/Aula13.qmd
            text: "Aula 13"


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual

