---
title: "IME05-12547/14149 Mineração de Dados"
---

Bom dia / Boa tarde / Boa Noite,

Aqui vocês vão encontrar alguns dos exemplos apresentados em aula, com uso do R. O objetivo é mostrar as possibilidades de aplicação do R nesta disciplina.

Os códigos apresentados em aula serão colocado por aqui também.

\[📖\] <a href="./semanas/Aula01.html" class="link">Explorando 01</a>

\[📖\] <a href="./semanas/Aula01A.html" class="link">Explorando 01A</a>

\[📖\] <a href="./semanas/Aula02.html" class="link">Explorando 02</a>

\[📖\] <a href="./semanas/Aula03.html" class="link">Explorando 03</a>

\[📖\] <a href="./semanas/Aula04.html" class="link">Explorando 04</a>

\[📖\] <a href="./semanas/Aula05.html" class="link">Explorando 05</a>

\[📖\] <a href="./semanas/Aula06.html" class="link">Explorando 06</a>

\[📖\] <a href="./semanas/Aula06A.html" class="link">Explorando 06A</a>

\[📖\] <a href="./semanas/Aula07.1.html" class="link">Regressão Simples</a>

\[📖\] <a href="./semanas/Aula07.2.html" class="link">Regressão Múltipla</a>

\[📖\] <a href="./semanas/Aula07.2.html" class="link">Validação Cruzada</a>

\[📖\] <a href="./semanas/Aula07.2A.html" class="link">Problemas na Regressão</a>

\[📖\] <a href="./semanas/Aula07.3.html" class="link">Seleção de Modelos</a>

\[📖\] <a href="./semanas/Aula07.4.html" class="link">Métodos de Encolhimento</a>

\[📖\] <a href="./semanas/Aula07.4A.html" class="link">Métodos de Encolhimento A</a>

\[📖\] <a href="./semanas/Aula08.0.html" class="link">Classificação 1os passos</a>

\[📖\] <a href="./semanas/Aula08.html" class="link">KNN</a>

\[📖\] <a href="./semanas/Aula09.html" class="link">Regressão Logística</a>

\[📖\] <a href="./semanas/Aula09A.html" class="link">SMOTE</a>

\[📖\] <a href="./semanas/Aula10.html" class="link">LDA e QDA</a>

\[📖\] <a href="./semanas/Aula11.1.html" class="link">Arvore de Regressão</a>

\[📖\] <a href="./semanas/Aula11.2.html" class="link">Arvore de Regressão GBM</a>

\[📖\] <a href="./semanas/Aula11.3.html" class="link">Arvore de Regressão XGBoost</a>

\[📖\] <a href="./semanas/Aula12.1.html" class="link">Arvore de Classificação</a>

\[📖\] <a href="./semanas/Aula12.2.html" class="link">Arvore de Classificação</a>

\[📖\] <a href="./semanas/Aula12.3.html" class="link">Arvore de Classificação XGBoost</a>

\[📖\] <a href="./semanas/Aula13.html" class="link">Análise de Clusters</a>

\[📖\] <a href="./semanas/Aula14.html" class="link">Análise de Associação</a>
