---
title: "Explorando Dados"
author: "Ricardo Accioly"
date: "`r Sys.Date()`"
format:
 html:
    code-link: true
    fig-width: 9
    fig-height: 7
    fig-dpi: 300
knitr:
  opts_chunk: 
    out.width: 90%
    comment: "#>"
execute:
  freeze: auto
---

## Carregando bibliotecas

```{r bibliotecas, message=FALSE}
library(tidyverse)
data(iris)
```

## O que temos aqui?

```{r 1, echo=TRUE}
head(iris)
iris %>% count(Species)
```

## Quais são as médias?

```{r 2}
iris %>% 
  group_by(Species) %>% 
  summarize(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))
```

## Vamos ver se temos alguma relação entre as variáveis

```{r 3}
iris %>% 
  group_by(Species) %>% 
  ggplot(aes(x=Sepal.Width, y=Sepal.Length, color=Species)) + 
  geom_point() +
  theme_minimal()
```

## Vamos ver se temos alguma relação entre as variáveis

```{r 3a}
iris %>% 
  group_by(Species) %>% 
  ggplot(aes(x=Sepal.Width, y=Sepal.Length, color=Species)) +
  geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "Relação entre Sepal Width e Sepal Length",
       x = "Largura (cm)",
       y = "Comprimento (cm)") +
  theme_minimal()
```

## Vamos ver se temos alguma relação entre as variáveis

```{r 4}
iris %>% 
  group_by(Species) %>% 
  ggplot(aes(x=Petal.Width, y=Petal.Length, color=Species)) + 
  geom_point() +
  theme_minimal()
```

## Vamos ver se temos alguma relação entre as variáveis

```{r 4a}
iris %>% 
  group_by(Species) %>% 
  ggplot(aes(x=Petal.Width, y=Petal.Length, color=Species)) +
  geom_point() + 
  geom_smooth(method = "lm") +
  labs(title = "Relação entre Petal Width e Petal Length",
       x = "Largura (cm)",
       y = "Comprimento (cm)") +
  theme_minimal()
```

## Vamos ver como se distribui o Petal.Width

```{r 5}
iris %>% 
  group_by(Species) %>% 
  ggplot(aes(x=Petal.Width, fill=Species)) +
  geom_histogram(color="Black") +
  theme_minimal()
```

## Vamos ver como se distribui o Petal.Length

```{r 6}
iris %>% 
  group_by(Species) %>% 
  ggplot(aes(x=Petal.Length, fill=Species)) + 
  geom_histogram(color="Black") +
  theme_minimal()
```
